services:
  frontend:
    image: dstensnes/asterisk:latest
    volumes:
      - conf:/etc/asterisk

volumes:
  conf:
    driver: local
    driver_opts:
      type: None
      o: bind
      device: ${CONF_PATH}

